#!/usr/bin/env bash
cd "$(dirname "$0")"

python3 -m pip install -r requirements.txt

export DZKP_PORT="${DZKP_PORT:-8080}"
export DZKP_SECRET_KEY="${DZKP_SECRET_KEY:-CHANGE_THIS_SITE_SECRET}"
export DZKP_API_SECRET="${DZKP_API_SECRET:-CHANGE_THIS_API_SECRET}"
export DZKP_API_READ_SECRET="${DZKP_API_READ_SECRET:-$DZKP_API_SECRET}"
export DZKP_API_WRITE_SECRET="${DZKP_API_WRITE_SECRET:-$DZKP_API_SECRET}"
export DZKP_ADMIN_USERNAME="${DZKP_ADMIN_USERNAME:-admin}"
export DZKP_ADMIN_PASSWORD="${DZKP_ADMIN_PASSWORD:-change-this-admin-password}"
export DZKP_PUBLIC_BASE_URL="${DZKP_PUBLIC_BASE_URL:-http://localhost:8080}"
export DZKP_DISCORD_CLIENT_ID="${DZKP_DISCORD_CLIENT_ID:-CHANGE_DISCORD_CLIENT_ID}"
export DZKP_DISCORD_CLIENT_SECRET="${DZKP_DISCORD_CLIENT_SECRET:-CHANGE_DISCORD_CLIENT_SECRET}"
export DZKP_DISCORD_REDIRECT_URI="${DZKP_DISCORD_REDIRECT_URI:-$DZKP_PUBLIC_BASE_URL/auth/discord/callback}"

python3 app.py
